### PR TITLE
Modify the code to use Python3

### PR DESCRIPTION
**Pull request by pfertyk**
Since I updated my Xubuntu to 16.04, this plugin stopped working. I modified the code a bit to make it work with Python3 (my version is 3.5.2) and now it works fine.

I didn't try to refactor the code at all, just to stop it from crashing. I find this plugin very useful and I hope this code change will help others too. If you don't plan to port the plugin to Python3 or if there are any other issues with this PR, please let me know.

### CODE REVIEW

**Comment by mgedmin** [comment]
I want to make this plugin work with both versions of Python.  Do you know any other Vim plugins that can do that?  I'd prefer to steal some ideas instead of reinventing the wheel.

(Personally, I did `apt install vim-gnome-py2` on Ubuntu 16.04 so that I could continue to use many other vim plugins that haven't been ported to Python 3 yet.)

**Comment by mgedmin** [comment]
I asked on IRC and learned that UltiSnips can do that.

Here's what they do: 
- https://github.com/SirVer/UltiSnips/blob/master/plugin/UltiSnips.vim#L13-L41
- https://github.com/SirVer/ultisnips/blob/master/autoload/UltiSnips.vim#L14-L15

**Comment by mgedmin** [comment]
Can you try git master and see if it works on Python 3?  I've tested it with Python 2 only so far (don't have a Python-3-capable vim handy).

**Comment by pfertyk** [comment]
I installed `mgedmin/pythonhelper.vim` and it seems to work correctly. The class and method names are displayed and GVim didn't break on startup (like it used to after Xubuntu was updated).

Good idea to make it work with both versions of Python, I didn't think of that (I usually use only Python3 for everything). I wanted to send you this code (from `fisadev/vim-isort`):

```
if has('python')
    command! -nargs=1 AvailablePython python <args>
    let s:available_short_python = ':py'
elseif has('python3')
    command! -nargs=1 AvailablePython python3 <args>
    let s:available_short_python = ':py3'
else
    throw 'No python support present, vim-isort will be disabled'
endif
```

but I can see that you have already found another example.

**Pull request closed without merging**
